# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='time.proto',
  package='time',
  syntax='proto3',
  serialized_pb=_b('\n\ntime.proto\x12\x04time\"\r\n\x0bTimeRequest\"\x1c\n\tTimeReply\x12\x0f\n\x07message\x18\x01 \x01(\t27\n\x04Time\x12/\n\x07GetTime\x12\x11.time.TimeRequest\x1a\x0f.time.TimeReply\"\x00\x62\x06proto3')
)




_TIMEREQUEST = _descriptor.Descriptor(
  name='TimeRequest',
  full_name='time.TimeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=33,
)


_TIMEREPLY = _descriptor.Descriptor(
  name='TimeReply',
  full_name='time.TimeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='time.TimeReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['TimeRequest'] = _TIMEREQUEST
DESCRIPTOR.message_types_by_name['TimeReply'] = _TIMEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeRequest = _reflection.GeneratedProtocolMessageType('TimeRequest', (_message.Message,), dict(
  DESCRIPTOR = _TIMEREQUEST,
  __module__ = 'time_pb2'
  # @@protoc_insertion_point(class_scope:time.TimeRequest)
  ))
_sym_db.RegisterMessage(TimeRequest)

TimeReply = _reflection.GeneratedProtocolMessageType('TimeReply', (_message.Message,), dict(
  DESCRIPTOR = _TIMEREPLY,
  __module__ = 'time_pb2'
  # @@protoc_insertion_point(class_scope:time.TimeReply)
  ))
_sym_db.RegisterMessage(TimeReply)



_TIME = _descriptor.ServiceDescriptor(
  name='Time',
  full_name='time.Time',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=65,
  serialized_end=120,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTime',
    full_name='time.Time.GetTime',
    index=0,
    containing_service=None,
    input_type=_TIMEREQUEST,
    output_type=_TIMEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIME)

DESCRIPTOR.services_by_name['Time'] = _TIME

# @@protoc_insertion_point(module_scope)
